server:
  port: 9001
spring:
  application:
    name: order-nacos
  # nacos注册发现配置
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public # 命名空间，默认是public
        group: DEFAULT_GROUP # 分组，默认是DEFAULT_GROUP
        ephemeral: false # 是否是临时实例，默认为true，,当修改为false也就是永久实例时，即使挂了，也不会从服务列表删除
        service: ${spring.application.name} # 注册到nacos的服务名
#        weight: 1 # 结合ribbon权重的负载均衡策略，权重越高，分配的流量越大