server:
  port: 9003
spring:
  application:
    name: order-ribbon
  # nacos注册发现配置
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public # 命名空间，默认是public
        group: DEFAULT_GROUP # 分组，默认是DEFAULT_GROUP
        ephemeral: false # 是否是临时实例，默认为true
        service: ${spring.application.name} # 注册到nacos的服务名
# ribbon配置
ribbon:
  eager-load:
    enabled: true # 设置为饥饿加载，默认情况下，第一次调用服务时才会动态加载ribbon策略，使用饥饿加载，可以在项目启动时就立即加载
    clients: stock-service # 饥饿加载的服务，多个服务时用都好隔开
# 修改默认的负载均衡策略，默认使用轮询的方式
#stock-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 基于随机&权重